### ISSUE TITLE
Error whe starting

### ISSUE THREAD

**Issue by chmod777john** [JerryI/wolfram-js-frontend#118]
**Describe the bug**
When starting the project, I encoutered this error.
```bash
@chmod777john ➜ /workspaces/wolfram-js-frontend (devcontainer) $ wolframscript -f Scripts/start.wls host 0.0.0.0 http 8080 ws 8081 ws2 8082 docs 8085 
>> LPM >> project directory >> /workspaces/wolfram-js-frontend
>> LPM >> last updated >> Sun 14 Apr 2024 22:12:01
>> CSockets >> Unix >> Linux-x86-64
>> CSockets >> Unix >> Loading library... LLink JustTryToFind

LibraryFunction::libload: The function run_uvloop was not loaded from the file /workspaces/wolfram-js-frontend/wl_packages/KirillBelov_CSockets/LibraryResources/7/Linux-x86-64/csockets.so.
>> CSockets >> Unix >> It did not work! LLink 7
>> CSockets >> Unix >> Trying LLink 6

LibraryFunction::libload: The function run_uvloop was not loaded from the file /workspaces/wolfram-js-frontend/wl_packages/KirillBelov_CSockets/LibraryResources/6/Linux-x86-64/csockets.so.
>> CSockets >> Unix >> Loading process failed. LLink 6
```

**To Reproduce**
Visit https://github.com/chmod777john/wolfram-js-frontend, then press `,`, Github will guide you to create a codespace with a clean environment. This can eliminate problems caused by differences in system environments.

Please read this guide: https://github.com/chmod777john/wolfram-js-frontend?tab=readme-ov-file#cloud-based-quick-start 

Finally when executing `wolframscript -f Scripts/start.wls host 0.0.0.0 http 8080 ws 8081 `, the error occured.

**Comment by JerryI** [comment]
Just a comment for other people. After the discussion, we have found that for network operations Wolfram Engine requires

`sudo apt-get install avahi-daemon`

it is also recommended by Wolfram Research

**Comment by JerryI** [comment]
And for some reason **only normal licensing using an email address is working properly** for both Wolfram Kernel

i will probably close this issue.

**Comment by JerryI** [comment]
Related #96
