### ISSUE TITLE
DateListPlot not outputing expected plot

### ISSUE THREAD

**Issue by gganapat** [JerryI/wolfram-js-frontend#141]
When I tried to plot a timeseries (power vs date), the expected output was blank. when I tried to reproduce the code in wolframscript directly, it worked fine.

The code I'm working with is 
```
cwd=Directory[]
file = StringJoin[cwd<>"/gwp.csv"]
dataraw=Import[file, "Data"];
data = Rest[dataraw];
date = #[[2]]& /@data;  (* Remove header "DATE" *)
time = #[[3]]& /@data; (* Remove header "START TIME" *)
power = #[[5]]& /@data; (* Remove header "USAGE" *)
dat = MapThread[(#1 <> " " <> #2) &, {date, time}];

datetime = 
 Table[DateObject[
   DateList[{dat[[i]], {"MonthShort", "/", "DayShort", "/", 
      "YearShort", " ", "HourShort", ":", "MinuteShort"}}]], {i, 
   Length[dat]}];
ts = TimeSeries[power, {datetime}];
Export["dateplot.png", DateListPlot[ts]] // OutputForm
```

The expected plot is 
<img width="360" alt="dateplot" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/91c2c14c-dca4-43ea-9390-9de87711f681">

I got this instead --

<img width="360" alt="dateplot" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/71f91dcc-279e-4200-a09f-f6631022c994">

I'm using Firefox on MacBookPro M1

Thanks,
Gani -

**Comment by gganapat** [comment]
And here is the data file I'm working with --

[gwp.csv](https://github.com/JerryI/wolfram-js-frontend/files/15205646/gwp.csv)

**Comment by JerryI** [comment]
It looks like I broke  some parts `DynamicBox` which is used when an image comes to a rasterization for some types of plots in a favor of other syntax sugar to work properly.

Well, it turned out to be easier to fully support `DateListPlot` in our framework. I have uploaded a new version already, here is how it works


https://github.com/JerryI/wolfram-js-frontend/assets/4111822/db957936-87ae-4f25-8d6e-eaa7fe20ac0b

**Comment by JerryI** [comment]
Basically, it means you can only plot it in a notebook and then save it as i did show in the video

**Comment by gganapat** [comment]
Hi!

Thanks a lot! Unfortunately, this didn't work for me. I downloaded the
latest version and when I tried to duplicate these steps, I got the message
"Loading..." and it didn't proceed. All data were processed correctly prior
to DateListPlot[ts]. Not sure why that happened.

Gani --

**Comment by JerryI** [comment]
Ah. cache probably.
Please, do hard reload (Shift+F5 i guess on firefox). This is a common problem, that browser caches all scripts for a loooong

**Comment by gganapat** [comment]
ok, that worked! Thanks again! Gani --

**Comment by JerryI** [comment]
If there are any other issues with `DateListPlot`, please, reopen it again ;)

**Comment by gganapat** [comment]
Ok thx. That worked.Gani-Sent from my iPhoneOn May 4, 2024, at 10:31 AM, Kirill Vasin ***@***.***> wrote:﻿
Ah. cache probably.
Please, do hard reload (Shift+F5 i guess on firefox). This is a common problem, that browser caches all scripts for a loooong

**Comment by gganapat** [comment]
Hi, something has changed since the last time this worked fine. Now, the plot doesn't render and I get this:

<img width="1103" alt="Screenshot 2024-05-11 at 11 32 44 AM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/8d8b3a62-fa8b-4457-ab67-4290ee812c83">

I cleared out the cache, re-installed wolfram-js-frontend and it didn't work.

Thanks, Gani --

**Comment by JerryI** [comment]
> Hi, something has changed since the last time this worked fine. Now, the plot doesn't render and I get this:
> 
> <img alt="Screenshot 2024-05-11 at 11 32 44 AM" width="1103" src="https://private-user-images.githubusercontent.com/46061218/329806837-8d8b3a62-fa8b-4457-ab67-4290ee812c83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NTI5NTgsIm5iZiI6MTcxNTQ1MjY1OCwicGF0aCI6Ii80NjA2MTIxOC8zMjk4MDY4MzctOGQ4YjNhNjItZmE4Yi00NDU3LWFiNjctNDI5MGVlODEyYzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDE4MzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxNDRmMmI5MzcyYzI5MTE0MDQwYWVhNzA4NzI3NmQ0MjQxYTRmOTE3MzhlYzk3NTQ1NzBkZThhOTU1Zjc3ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rlUliwzYCU0Xzl_J309zYu7rU9Eum_7vZvGHzePg8V0">
> I cleared out the cache, re-installed wolfram-js-frontend and it didn't work.
> 
> Thanks, Gani --

Hi Gani,
I think there is a typo
`DateListPlot`

**Comment by JerryI** [comment]
Since this is undefined symbol, it tries to render the output as it as

**Comment by gganapat** [comment]
Thanks for the response. I had mistyped the last time. The length of power is 5435, but trying to plot more than 1700 points fails.

<img width="636" alt="Screenshot 2024-05-11 at 11 53 58 AM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/d80c3735-a03e-4dcc-9fa0-0274c0fbac61">

When trying for 1800 points, generating TimeSeries fails --

<img width="1095" alt="Screenshot 2024-05-11 at 11 56 24 AM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/79ef0d9c-e9d3-46b0-aeb1-d83c5ab8a78d">

thanks, gani -

**Comment by gganapat** [comment]
Yes, you are right again! The plotting works.

Thanks!

**Comment by JerryI** [comment]
This is protection mechanism, which cuts the output if it is too large so that it won't slow down the editor. 

We need to implement a feature, when the inner data of a symbol will be serialised to a file or something like that and only the reference will be kept in the cell. It must be an easy fix...

**Comment by JerryI** [comment]
Fixed!
