### ISSUE TITLE
License Error when Running Wolfram Engine 14 with WLJS

### ISSUE THREAD

**Issue by pyreymo** [JerryI/wolfram-js-frontend#162]
I am encountering an issue when trying to run Wolfram Engine 14.0 with WLJS. Despite having successfully activated WE locally, I am receiving a license error. Here are the details of the error message:

![image](https://github.com/JerryI/wolfram-js-frontend/assets/45317256/59283b6d-3b4e-4150-90d0-4d5ff4fedb69)

WLJS laucher paused because of a license error.

Steps I have taken to resolve the issue:
1. Verified that the license is correctly activated locally.
   ![image](https://github.com/JerryI/wolfram-js-frontend/assets/45317256/0282b46d-af7e-450f-bafd-c3372d3299a8)
2. Attempted to run the application as an administrator.

Unfortunately, these steps have not resolved the issue. I suspect there may be an issue with how the license is being verified or with the integration between WLJS and Wolfram Engine 14.0.

I am relatively new to Wolfram Engine and this project, so I apologize in advance if this issue is due to any basic mistakes on my part. Any guidance or suggestions would be greatly appreciated.

**Comment by pyreymo** [comment]
[2minutesLog.txt](https://github.com/JerryI/wolfram-js-frontend/files/15312061/2minutesLog.txt)

**Comment by JerryI** [comment]
Hello @pyreymo,
We are sorry about that, it looks like a bug. We have seen before, that sometimes Wolfram Engine does not allow to run 2 instances on the same machine for no reason (WLJS requires exactly 2), but quite rare. 

We will prepare a test script for you to diagnose a problem and will try our best to help you :)

PS: thank you for log file

**Comment by JerryI** [comment]
Could you, please, try to download [this repo](https://github.com/JerryI/wl-wlx) and run the following demo (just directly by double-click) ?

```
Examples/Balls/Balls.wls
```

And after it finishes an installation, open [http://127.0.0.1:8010](http://127.0.0.1:8010) page in the browser.

**Comment by pyreymo** [comment]
It seems to work without any errors, the ball follows the mouse to create and then moves normally after I checked "Gravity".

![image](https://github.com/JerryI/wolfram-js-frontend/assets/45317256/73df8d1b-94a7-474b-b5f9-57f3d1966925)



This file [Balls.log](https://github.com/JerryI/wolfram-js-frontend/files/15323571/Balls.log) shows all the displays after I run `Examples/Balls/Balls.wls`.

**Comment by pyreymo** [comment]
I edited my `_settings.wl` to `<|"Autostart" -> False|>` and restarted the WLJS launcher. However, I am still encountering the license error, though it appears slightly different this time.

![image](https://github.com/JerryI/wolfram-js-frontend/assets/45317256/7d1310de-c5b7-43bb-9fb1-c50909e8b012)

Here is the full log:
[Launcher.log](https://github.com/JerryI/wolfram-js-frontend/files/15337368/Launcher.log)

**Comment by JerryI** [comment]
If you still have motivation, I would love to ask you to do a few more tricks. You are helping us a lot and other users, who could face similar issues.

If not - it is fine, we don't want to steal your time. Thank you again. 

**Tricks** (just in case)
Since it fails at `Autotest`, could you please edit the file

`C:\\Users\<YourName>\AppData\Roaming\wljs-notebook\Scripts\start.wls`

and delete following lines

<img width="489" alt="Screenshot 2024-05-16 at 18 43 55" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/512821b7-d6e0-47d1-bcd3-58242287b0f2">

It will bypass an autotest and we might see some reasonable answer and which part of a stack is malfunctioning.

**Comment by JerryI** [comment]
*stale*
