### ISSUE TITLE
Can't use Azure OpenAI endpoint

### ISSUE THREAD

**Issue by allenwoods** [JerryI/wolfram-js-frontend#173]
**Describe the bug**
I have configured the endpoint and model name for Azure OpenAI in the settings (which work fine in other software), and after inputting the "reset chat" command, I pasted the OpenAI API key, but it shows "API invalid".

To Reproduce
As described above.

**Expected behavior**
The chat interface should display normally.

**Screenshots**
<img width="794" alt="image" src="https://github.com/JerryI/wolfram-js-frontend/assets/7327215/a8c94134-596a-4301-b58e-3bd9f15bdea5">

<img width="377" alt="image" src="https://github.com/JerryI/wolfram-js-frontend/assets/7327215/a6213769-6c37-49a2-b3f2-f792adadddce">

**Desktop (please complete the following information):**
 - OS: MacOS X
 - Desktop App

**Comment by allenwoods** [comment]
Thanks for the prompt reply! It did show my API key, but the Azure OpenAI API key consists of only 32 characters.

**Comment by JerryI** [comment]
Fixed in [#wljs-snippets](https://github.com/JerryI/wljs-snippets/commit/86ac1616dd2706a03e7d394f41c6e3230e3f16d9)

Please force update check from settings menu and then on the next start of an app it will fetch a new version.
