### ISSUE TITLE
ChartLabels

### ISSUE THREAD

**Issue by JerryI** [JerryI/wolfram-js-frontend#181]
Hi:
I'm trying to place ChartLabels in specific position like Top since the default option is not rendering too well. So, my default version looks like this:

<img width="721" alt="Screenshot 2024-05-23 at 11 30 23 AM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/437c37c6-ead5-40ee-9e35-745eb9bafabd">

But when I try to place the labels at the top, I get this:

<img width="847" alt="Screenshot 2024-05-23 at 11 30 51 AM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/98c2366c-052b-4855-9a38-ff74603517c3">

Any help would be appreciated.

Thx!
Gani -

_Originally posted by @gganapat in https://github.com/JerryI/wolfram-js-frontend/discussions/178_

**Comment by JerryI** [comment]
<img width="511" alt="Screenshot 2024-05-25 at 14 52 51" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/e75a8150-c97a-4ac4-9d21-7d9798547ec7">

Fixed in a new release

@gganapat

**Comment by gganapat** [comment]
Great! That fixed it.

thx, gani-
