### ISSUE TITLE
Exporting a Notebook that includes MalipulatePlot or Interractive illustrations as an HTML

### ISSUE THREAD

**Issue by ganiba** [JerryI/wolfram-js-frontend#191]
**Related problem to the requested feature**

When i Export a Notebook that includes ManipulatePlot or any interractive illustrations as an HTML file such as "Manipulate.wln"

<img width="1030" alt="Screenshot 2024-06-03 at 11 40 43" src="https://github.com/JerryI/wolfram-js-frontend/assets/16179150/1c313ada-71ba-49bd-a456-84efe0c9b3ce">

and opened it on Google Chrome or Firefox, It only shows the codes and not the interactive illustration, and instead it shows "Loading ..."

<img width="1440" alt="Screenshot 2024-06-03 at 11 42 04" src="https://github.com/JerryI/wolfram-js-frontend/assets/16179150/50e8ac39-0906-4753-b03c-6358ed475bfb">

**Suggested solution**
As i understand, such WLJS functions needs wolfram kernel and will not work as pure html page. However, can we have make a connexion between the HTML file and the installed Wolfram Kernel.

**Comment by JerryI** [comment]
https://github.com/user-attachments/assets/e44a52fe-ca3e-43fb-8e5e-2fa1bde72e94

We have some progress on that. _Note that there is no Wolfram Kernel running._

**Comment by ganiba** [comment]
Great job.

Thanks a lot for your efforts,


Ghassane.

---

*Ghassane Aniba, Eng. Ph.D. SMIEEE*
Full Professor, Electrical Department
Mohammadia School of Engineers (EMI)
Mohammed V University in Rabat
Emails:   ***@***.***
               ***@***.***
Linkedin profile:  https://www.linkedin.com/in/ganiba/
Mobile: + 212 (0)7 07 26 42 24
Fax:     + 212 (0)5 37 77 88 53

**Comment by JerryI** [comment]
Thank you, @ganiba 😀

We are close to releasing it.
The approach works with any kind of dynamics. It determines all connections by recording interacting session and then samples all output data based on any possible combination of the input data.

https://github.com/user-attachments/assets/ac2f26f7-0be7-4f80-8b71-a0cb16e4f039

Then it builds sort of a state machine and a look-up table (compressed using gzip), which mimics replies of a real Wolfram Kernel. 

--

Kirill

**Comment by JerryI** [comment]
https://github.com/user-attachments/assets/9a3103c5-60bd-463e-8b77-26c3499f82b2

Yet another feature is on the way, if you don't want to deal with the previous routine. Here is a simple and straightforward solution coming `AnimatePlot` and `AnimateParametericPlot`. It bakes all data to the notebook, which can be exported normally.

**Comment by JerryI** [comment]
Released!

some options to choose from
- [AnimatePlot](https://jerryi.github.io/wljs-docs/frontend/Reference/Plotting%20Functions/AnimatePlot)
- ListAnimatePlot
- [Dynamic HTML](https://jerryi.github.io/wljs-docs/frontend/Exporting/Dynamic%20HTML)
