### ISSUE TITLE
Activate wolfram engine from the WLJS

### ISSUE THREAD

**Issue by freddyholms** [JerryI/wolfram-js-frontend#192]
**Is your feature request related to a problem? Please describe.**
I want to package the wolfram engine and WLJS into a docker image that I can share with some friends. Unfortunately, this is not currently possible as wljs cannot launch until the engine has been activated. At least that happens to me when following the instructions on this repo. 

**Describe the solution you'd like**
Ideally they would just docker run my image, and go to the specified port on their browser, from where they could activate the engine with their id.

**Comment by JerryI** [comment]
Probably it is a bug. It should be possible to activate Engine from WLJS, a special form should appear in such case. Could you, please, show the screenshot from the launcher?

Docker, yes, we also tried in this direction. Good idea. Another possibility would be to also implement automatic activation using somewhat like temp-mail API…

**Comment by JerryI** [comment]
related #59 and #96

**Comment by JerryI** [comment]
I will post here the current state of Docker image

We have now a Docker file made by Roman Dyakov

```
FROM wolframresearch/wolframengine:13.3.0

WORKDIR /app/wolfram-js-frontend

USER root
RUN apt-get update \
    && apt-get install -y curl git \
    && git clone https://github.com/JerryI/wolfram-js-frontend.git /app/wolfram-js-frontend

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "curl", "-f", "http://localhost" ]
CMD [ "wolframscript", "-f", "/app/wolfram-js-frontend/Scripts/start.wls", "host", "0.0.0.0", "http", "8080", "ws", "8081", "ws2", "8082", "docs", "8085" ]
```

and a configuration file

```
version: '3'

services:
  wljs-notebook:
    image: wljs-notebook:1.0
    tty: true
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8085:8085"
```

The only problem we have now is how to activate WL. There is a solution from WRI, but it is quite [cumbersome](https://hub.docker.com/r/wolframresearch/wolframengine) (see Activate Using Node-Locked Licensing).

I am not an expert on Docker, but I believe the process of activation can be automated with a user dialog somehow...

**Comment by JerryI** [comment]
*stale*
