### ISSUE TITLE
Kernel is not connected 

### ISSUE THREAD

**Issue by JerryI** [JerryI/wolfram-js-frontend#198]
I see there is a new release 2.4.2 in Homebrew.  After updating WLJS tried to run it but unfortunately, ever since the last release 2.3.7 there has always been an error connecting to the kernel (Wolfram Engine / Mathematica Kernel). I.e. trying to execute "2+2" first prompts "Select Kernel", and then after selecting the only option available: "Auto", the next message is "Alert: Kernel container is not ready!". Clicking on "Refresh window" does not help. It's been so ever since the previous Homebrew version... WLJS used to work fine before.

_Originally posted by @jvo203 in https://github.com/JerryI/wolfram-js-frontend/issues/193#issuecomment-2171065291_

**Comment by JerryI** [comment]
>I see there is a new release 2.4.2 in Homebrew. After updating WLJS tried to run it but unfortunately, ever since the last release 2.3.7 there has always been an error connecting to the kernel (Wolfram Engine / Mathematica Kernel). I.e. trying to execute "2+2" first prompts "Select Kernel", and then after selecting the only option available: "Auto", the next message is "Alert: Kernel container is not ready!". Clicking on "Refresh window" does not help. It's been so ever since the previous Homebrew version... WLJS used to work fine before.

We are sorry about that. This is also a bit odd, since I am building it on Mac. ;)
However, there must be an easy solution. Could you, please, restart an app and click on a big button `Debug` on the launcher window.

It will start collecting log. Then just do what you normally do to cause an error, after that close an application and it will produce a log file (a window will pop up). Check it if there is any sensitive information inside and share it with me (here or by email krikus.ms@gmail.com ).

**Comment by JerryI** [comment]
@jvo203

**Comment by jvo203** [comment]
Hi, attached is a whole System.log. Indeed it does look a bit "suspicious" in a few places. For completeness, the standalone Wolfram Engine works fine:
```
(venv) chris@studio ~ % wolframscript
Wolfram Language 14.0.0 Engine for Mac OS X ARM (64-bit)
Copyright 1988-2023 Wolfram Research, Inc.

In[1]:= 2+2

Out[1]= 4

In[2]:=
```
[System.log](https://github.com/user-attachments/files/15856451/System.log)

**Comment by JerryI** [comment]
found

```
/Users/chris/Library/Mathematica/Licensing/mathpass:3:
password file "/Users/chris/Library/Mathematica/Licensing/mathpass".
	Invalid password.
```

~~Thank you again, Wolfram~~ 

Probably you have checked it already, but just in case: do you have any other instance of Wolfram Kernel running? Wolfram License limits the number of running Kernels to 2. WLJS-Notebook uses exactly 2.

**Comment by jvo203** [comment]
That's strange. There is no active Wolfram Mathematica session running on this machine, and no active Wolfram Engine either. Running ps does not show up any running kernels either, not on this machine and not on any other machines ...
```
(venv) chris@vpn-39-138 ~ % ps -uchris | grep Kernel
  501  4793 ttys009    0:00.00 grep Kernel
(venv) chris@vpn-39-138 ~ % ps -uchris | grep Wolfram
  501  4809 ttys009    0:00.00 grep Wolfram
(venv) chris@vpn-39-138 ~ % ps -uchris | grep Mathematica
  501  4830 ttys009    0:00.00 grep Mathematica
(venv) chris@vpn-39-138 ~ %
```

**Comment by jvo203** [comment]
But you are right, there must be a left-over Wolfram Kernel running somewhere since attempting to launch two Wolfram scripts fails:
```
(venv) chris@studio ~ % wolframscript
Wolfram Language 14.0.0 Engine for Mac OS X ARM (64-bit)
Copyright 1988-2023 Wolfram Research, Inc.

In[1]:= 2
Out[1]= 2

In[2]:= 2+1

Out[2]= 3

In[3]:=
``` 
and trying to open the second one:
```
(venv) chris@vpn-39-138 ~ % wolframscript

Your Wolfram product is not activated or is experiencing a license-related problem.

Please activate the product at the following WolframKernel location:

    /Applications/Mathematica.app/Contents/MacOS/WolframKernel

(venv) chris@vpn-39-138 ~ %
```
I need to look harder on various machines to search for a ghost Wolfram session.

**Comment by jvo203** [comment]
There are no active sessions running anywhere but I think I know what is causing this problem. Recently (on the 1st of June) my Mathematica plan got changed automatically from the Premier Service to this new licensing plan that Wolfram has been rolling out for the past year or so. As part of Premier Service I got one license at work and one license at home. It seems the previous right to run two Wolfram Engines has kind of disappeared in to a black hole.

I probably need to re-apply for a free Wolfram Engine user account (perhaps using a different email address). So let's close this issue as it seems it is not caused by any problems with the WLJS as such. It is a Wolfram licensing problem.

I cannot close this issue from GitHub, it has to be done by you.

**Comment by JerryI** [comment]
I faced similar issue in a past. Nowadays from time to time WL doesn't want to start a second kernel if I have an active internet connection. The same I've seen happening in Jupyter Notebook + WL. WRI is very enthusiastic when it comes to licensing problems.

I hope it won't cause any troubles with Mathematica instance. If it will, please, open a new issue. There is a way on how to run `wolframscript` with explicitly given `-username -password`, so that you can rely on other account when use WLJS Notebook. I can try to implement it in the client App.
