### ISSUE TITLE
Print[] creates a popup rather than a new line

### ISSUE THREAD

**Issue by LoganJFisher** [JerryI/wolfram-js-frontend#206]
**Describe the bug**
When I use a Print[] command (e.g. Print[Hello, World!]), a popup is created that reads out the print message for a moment and then disappears. This is in contrast to how Mathematica works, where it simply creates a new line just as it would if I had entered 2+2 instead.

**To Reproduce**
Print[Hello, World!]

**Expected behavior**
On a new line: Hello, World!

**Screenshots**
![bzKJboU](https://github.com/JerryI/wolfram-js-frontend/assets/63993409/c890d2c5-e389-4cc8-8a1b-b375bd43c76e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Desktop App

**Comment by JerryI** [comment]
I believe we need to consider both options to be selected by a user. This is a good suggestion.
As a temporal solution, try to use [`CellPrint`](https://jerryi.github.io/wljs-docs/frontend/Reference/Cells%20and%20Notebook/CellPrint)

**Comment by JerryI** [comment]
<img width="22" alt="Screenshot 2024-06-22 at 11 28 32" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/12a1dbe8-e3a7-4883-aafb-dfb9b5c2d370">

By the way, if you click there, it will open notification sidebar with all messages ever printed in the current window.

**Comment by LoganJFisher** [comment]
Thanks for suggesting CellPrint. It's not perfect, but it's a sufficient temporary solution.

**Comment by JerryI** [comment]
<img width="524" alt="Screenshot 2024-06-24 at 10 55 10" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/bbf0dac9-7207-4666-80b0-6d0883f5b7d2">
somewhat like this, right?

**Comment by LoganJFisher** [comment]
Yeah, that looks good!

**Comment by JerryI** [comment]
Oki. it will be in a new release soon

**Comment by LoganJFisher** [comment]
Thanks! I hope I've not overwhelmed you with this and the other suggestions. I really do appreciate the hard work you've put into this. 🙂

**Comment by JerryI** [comment]
No ;) This is absolutely fine. New suggestions, issues - all this means that someone is using this project and it is worth to develop further. Also it helps to distribute priorities.
