### ISSUE TITLE
"Evaluate all cells" button

### ISSUE THREAD

**Issue by LoganJFisher** [JerryI/wolfram-js-frontend#208]
**Is your feature request related to a problem? Please describe.**
Unless I'm mistaken, there is currently no way to evaluate all cells in one go. Rather, each block needs to be evaluated manually and individually.

**Describe the solution you'd like**
A button to be added to the top bar that can be clicked to evaluate all cells in the active workbook.

**Additional context**
![Mo4GBHy](https://github.com/JerryI/wolfram-js-frontend/assets/63993409/eddc0a18-4f85-42f0-9b1f-3518ad3e1b23)

**Comment by JerryI** [comment]
<img width="235" alt="Screenshot 2024-06-22 at 23 35 18" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/79d50060-44e3-43ea-a4e5-94073a29da0b">

It must be in the top menu. On Windows it is located at the top left corner. There is also a hot-key `Alt+a`

**Comment by LoganJFisher** [comment]
Oh, I see. I need to flag the cells I want as _initialization cells_. I misunderstood how this functions works. Thanks.

**Comment by JerryI** [comment]
Then, locate … three dots on the left side of a cell. There will be a drop down menu. :)

**Comment by JerryI** [comment]
A green dot will appear on the input cell. Then you can evaluate all initialization cell from the same top menu (top left corner)

**Comment by JerryI** [comment]
<img width="826" alt="Screenshot 2024-06-23 at 10 20 42" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/1d0c5e3d-fc8d-467d-8d44-2659df69bc3f">
