### ISSUE TITLE
Plot3D clipping issue

### ISSUE THREAD

**Issue by LoganJFisher** [JerryI/wolfram-js-frontend#209]
**Describe the bug**
I'm not entirely sure what causes it, but when I try to do a Plot3D with a lot of curvature or a large area, it seems to have clipping issues

**To Reproduce**
Plot3D[k^2 + n^3, {k, 0, 10}, {n, 0, 10}]

**Expected behavior**
No clipping

**Screenshots**
![dUd7GYm](https://github.com/JerryI/wolfram-js-frontend/assets/63993409/e5b9200a-b0ae-4008-b516-468f3bb0ee52)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Desktop App

**Comment by JerryI** [comment]
Fixed in a new release of `wljs-graphics3d-threejs`. Please, force check updates from the settings menu to get a new version and then reset cache (Top menu `->` Reload)

**Comment by LoganJFisher** [comment]
Just ran some tests and it seems to work perfectly now. Thanks!

**Comment by LoganJFisher** [comment]
Just ran some tests and it seems to work perfectly now. Thanks!
