### ISSUE TITLE
Documentation tooltips

### ISSUE THREAD

**Issue by LoganJFisher** [JerryI/wolfram-js-frontend#211]
**Is your feature request related to a problem? Please describe.**
This isn't necessarily a problem, but is a nice-to-have native to Mathematica that I would like to see implemented into WLJS.

Note:  Maybe not in Mathematica? It's at least in WolframCloud, which is currently all I have access to via an old academic license that never expired.

**Describe the solution you'd like**
In Mathematica, when you type a function (e.g. Integrate[]), if you place your cursor between the square brackets (either using arrow keys or mouse), a tooltip appears that allows you to either open a dropdown that explains the possible entries into that function, or to open a side menu that displays the Wolfram language documentation for that function. I would like to see this implemented into WLJS.

**Additional context**
![ICsleEQ](https://github.com/JerryI/wolfram-js-frontend/assets/63993409/8d9430f4-1728-4696-b839-3a746fe431f6)
![FqURjcJ](https://github.com/JerryI/wolfram-js-frontend/assets/63993409/3683b2e1-93e1-48d6-b015-51700a7a5ad3)
![m6PFb3d](https://github.com/JerryI/wolfram-js-frontend/assets/63993409/51bdff60-140d-4fd6-a99c-3bf8ca2d88d6)

**Comment by JerryI** [comment]
<img width="729" alt="Screenshot 2024-07-23 at 12 44 07" src="https://github.com/user-attachments/assets/a87a8185-c5e7-4d88-8721-c7b90d7d89c3">

Most probably the fastest solution will be to insert links into autocomplete.
Other users are welcome as well to join the discussion

**Comment by JerryI** [comment]
and use [Tooltips](https://codemirror.net/examples/tooltip/) as well

**Comment by JerryI** [comment]
Added in a new release

![Screenshot 2024-08-19 at 12 33 09](https://github.com/user-attachments/assets/9c9531bf-183e-4c5b-8607-2ed788f03bb0)


By clicking on it, a new window will be opened
