### ISSUE TITLE
ListPointPlot3D not rendering

### ISSUE THREAD

**Issue by gganapat** [JerryI/wolfram-js-frontend#213]
**Describe the bug**
Subject title

**To Reproduce**
ListPointPlot3D[Table[Sin[j^2 + i], {i, 0, 3, 0.1}, {j, 0, 3, 0.1}]]

<img width="935" alt="Screenshot 2024-06-23 at 9 36 04 AM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/a09f2515-3c36-4b84-a06c-a8d04cbc97d9">

**Expected behavior**
A rendered plot as below
<img width="515" alt="Screenshot 2024-06-23 at 9 35 18 AM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/0b064dce-8967-4b87-b744-5513a6cc71b1">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox

**Comment by JerryI** [comment]
Fixed in a new release of `wljs-graphics3d-threejs`
