### ISSUE TITLE
How do I utilize the "code editor improvements"?

### ISSUE THREAD

**Issue by LoganJFisher** [JerryI/wolfram-js-frontend#248]
**Describe the bug**
Update 2.5.0 includes "code editor improvements", and a gif shows it in action, formatting inputs with square roots, fractions, etc. as you type. What I type is just appearing in-line.

**To Reproduce**
Type an input.

**Expected behavior**
Formatted input.

**Screenshots**
![eSVgJLk](https://github.com/user-attachments/assets/b10bb6de-5f83-4b61-9363-f4315ad594a8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Desktop App

I downloaded and ran WLJS.Notebook.Setup.2.5.0.exe, but so far as I can tell there's no way to check version within WLJS.

Possibly related: Ctrl+Alt+Space isn't opening a prompt window.

**Comment by JerryI** [comment]
The key is shortcuts

### Shortcuts
Alt+2, Cmd+2 hide/show input cell
Ctrl+/ make fraction on selected
Ctrl+6 make superscript on selected
Ctrl+2 make square root on selected
Ctrl+- make subscript on selected

We copied them from Mathematica 1:1. Just try to select an expression and apply one of the combinations. You can navigate into them using arrows.

For more complicated expressions such as integrals, you need to call a command palette and type `Special characters`. 

For greek symbols you can use `ESC+a` then in the autocomplete window you can click on the corresponding greek letter. Or also one can you a command palette.


PS: prompt window might be a bug...
PPS: I updated Readme.md with shortcuts

**Comment by JerryI** [comment]
PPPS: To insert matrix, there is also a special widget in the command palette

**Comment by JerryI** [comment]
Feel free to reopen if you have any troubles
