### ISSUE TITLE
The Wolfram Engine exited because of a license error

### ISSUE THREAD

**Issue by kintopp** [JerryI/wolfram-js-frontend#265]
I've been trying to get the front-end to recognise my WolframEngine + WolframScript installation to no avail. I always end up with, 'The Wolfram Engine exited because of a license error'.

My set-up is Mac OSX x86 (64-bit) MacBook Pro, with WolframScript 1.11.0 and WolframEngine v14.0.0 installed and activated on OSX v14.5 with v.2.4.5 of the wolfram-js-front-end. I've looked around in the older issues and although I can see that some others have run into this as well, I wasn't able to find instructions for how to resolve the problem. I'd be happy to help troubleshoot. 

Below is what I see after I reinstall the front-end.

Wolfram Language 14.0.0 Engine for Mac OS X x86 (64-bit)
Copyright 1988-2023 Wolfram Research, Inc.
In[1]:=
>> LPM >> project directory >> /Users/abosse/Library/Application\
 
>    Support/wljs-notebook
>> LPM >> fetching paclet infos...
>> LPM >> fetching info by KirillBelovTest/Objects on a Github...
>> LPM >> fetching info by JerryI/Internal on a Github...
>> LPM >> fetching info by JerryI/TCPServer on a Github...
>> LPM >> fetching info by JerryI/HTTPHandler on a Github...
>> LPM >> fetching info by JerryI/WebSocketHandler on a Github...
>> LPM >> fetching info by JerryI/CSocketListener on a Github...
>> LPM >> fetching info by JerryI/wl-wlx on a Github...
>> LPM >> fetching info by JerryI/wl-misc on a Github...
>> LPM >> fetching info by JerryI/wl-wljs-packages on a Github...
>> LPM >> checking cached
>> LPM >> fetching a zip archive from the master branch...
>> LPM >> extracting...
>> LPM >> copying... from /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/___temp/KirillBelovTest-Objects-3409821/ to\
 
>    /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/wl_packages/KirillBelov_Objects
LPM >> finished!
>> LPM >> fetching a zip archive from the master branch...
>> LPM >> extracting...
>> LPM >> copying... from /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/___temp/JerryI-Internal-ff70670/ to\
 
>    /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/wl_packages/KirillBelov_Internal
LPM >> finished!
>> LPM >> fetching a zip archive from the master branch...
>> LPM >> extracting...
>> LPM >> copying... from /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/___temp/JerryI-TCPServer-d6b9ced/ to\
 
>    /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/wl_packages/KirillBelov_TCPServer
LPM >> finished!
>> LPM >> fetching a zip archive from the master branch...
>> LPM >> extracting...
>> LPM >> copying... from /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/___temp/JerryI-HTTPHandler-9d8b836/ to\
 
>    /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/wl_packages/KirillBelov_HTTPHandler
LPM >> finished!
>> LPM >> fetching a zip archive from the master branch...
>> LPM >> extracting...
>> LPM >> copying... from /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/___temp/JerryI-WebSocketHandler-2ed4dd1/ to\
 
>    /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/wl_packages/KirillBelov_WebSocketHandler
LPM >> finished!
>> LPM >> fetching a zip archive from the master branch...
>> LPM >> extracting...
>> LPM >> copying... from /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/___temp/JerryI-CSocketListener-29a2acc/ to\
 
>    /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/wl_packages/KirillBelov_CSockets
LPM >> finished!
>> LPM >> fetching a zip archive from the master branch...
>> LPM >> extracting...
>> LPM >> copying... from /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/___temp/JerryI-wl-wlx-1e9cc8c/ to\
 
>    /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/wl_packages/JerryI_WLX
LPM >> finished!
>> LPM >> fetching a zip archive from the master branch...
>> LPM >> extracting...
>> LPM >> copying... from /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/___temp/JerryI-wl-misc-02f6825/ to\
 
>    /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/wl_packages/JerryI_Misc
LPM >> finished!
>> LPM >> fetching a zip archive from the master branch...
>> LPM >> extracting...
>> LPM >> copying... from /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/___temp/JerryI-wl-wljs-packages-b0c3e16/ to\
 
>    /Users/abosse/Library/Application\
 
>    Support/wljs-notebook/wl_packages/JerryI_WLJSPM
LPM >> finished!
>> CSockets >> Unix >> MacOSX-x86-64
>> CSockets >> Unix >> Loading library... LLink JustTryToFind

LibraryFunction::libload: 
   The function run_uvloop was not loaded from the file 
    /Users/abosse/Library/Application
     Support/wljs-notebook/wl_packages/KirillBelov_CSockets/LibraryResources/7
     /MacOSX-x86-64/csockets.dylib.
>> CSockets >> Unix >> It did not work! LLink 7
>> CSockets >> Unix >> Trying LLink 6
LibraryFunction::libload: 
   The function run_uvloop was not loaded from the file 
    /Users/abosse/Library/Application
     Support/wljs-notebook/wl_packages/KirillBelov_CSockets/LibraryResources/6
     /MacOSX-x86-64/csockets.dylib.
>> CSockets >> Unix >> Loading process failed. LLink 6
The Wolfram Engine exited because of a license error.

**Comment by kintopp** [comment]
I tried one more thing. Deleted WolframEngine and WolframScript and front-end completely. Created a new Wolfram user account. Installed WolframEngine and WolframScript and activated it with the new Wolfram user account. Installed v2.5.0 front-end. Pointed it to WolframScript binary, same error as before.

**Comment by JerryI** [comment]
Thank you for the detailed info!
This error message usually has nothing to do with a license, but just a default message thrown on any exceptions.

By looking into logs I see an issue,probably we need to recompile libuv for OSX x86 on Wolfram Engine 14. I have this machine around and going to test it.

**Comment by JerryI** [comment]
![Screenshot 2024-08-08 at 11 10 25](https://github.com/user-attachments/assets/d54fbd1e-ed40-4192-bcaa-acdd4fbd0dea)

I have removed the dust from my hackintosh x86, and it looks it is working.
I have updated the libraries with new one. If you just click `reinstall` on the launcher's window (assuming you are using one from the [releases](https://github.com/JerryI/wolfram-js-frontend/releases)) during the startup it should download all fresh libraries.

![Screenshot 2024-08-08 at 11 12 35](https://github.com/user-attachments/assets/57266547-2a9d-49e6-a9f3-8459d0a4f798)

**Comment by JerryI** [comment]
I am glad it have been resolved. :)
However, this is still a mystery for me...

A desktop application acts more like a wrapper over a web-server (WLJS Notebook). Since there is no big changes to this wrapper from version to version, we update the core (web server + supporting libs) separately. Then users do not have to redownload the whole bundle.
