### ISSUE TITLE
Issue with Installation Process: Stuck During Initial Launch on `wolfram-js-frontend`

### ISSUE THREAD

**Issue by singularitti** [JerryI/wolfram-js-frontend#273]
I am writing to report an issue I have encountered with the installation process of the `wolfram-js-frontend` app on macOS. After downloading the app and launching it for the first time, the installation process gets stuck at the following output:

```
Downloading .zip archive to ~/Library/Application Support/wljs-notebook...
+ | 14
File successfully downloaded
Unzipping...
```

<img width="712" alt="image" src="https://github.com/user-attachments/assets/ef9c8da2-72ff-4324-97d3-2e1ca525893c">

Unfortunately, the installation does not proceed beyond this point, and the app seems to be stuck indefinitely.

Here are the details of my environment and the steps I took:

- **macOS Version:** Sonoma 14.6.1
- **App Versions Tested:** 2.4.5 and 2.5.0
- **Hardware:** Tested on both Intel and ARM-based Macs
- **App Images Used:** Both minimal and normal app images

The issue persists across different versions, Mac architectures, and app images. I have attached a screenshot of the installation process where the app gets stuck.

Please let me know if there are any additional steps I can take to resolve this issue or if you need further information.

**Comment by JerryI** [comment]
Hi @singularitti,
We are sorry about this. Could you please try to run it from the terminal?

```bash
'./Applications/WLJS Notebook.app/Contents/MacOS/WLJS Notebook'
```

It will print more information about what happens inside

There will be more logs provided. I believe it supposed to be a bug with a module, that downloads this package, or some issues with rights.

**Comment by JerryI** [comment]
Hm... I think I see the reason.
Could you please just try again? :) We dropped `updates` branch and left only `main`. Most probably an old instance of WLJS Notebook wrote to a config file an old branch name and then the launcher application tries to fetch it from there.

I put back `updates`. now it should work. We will fix this issue in a new release!

**Comment by singularitti** [comment]
It works now, thank you @JerryI!
