### ISSUE TITLE
Too Long To Display but the list is only 4 objects

### ISSUE THREAD

**Issue by Hachann** [JerryI/wolfram-js-frontend#282]
Hello guys,

I have an Association of Length 4. I can display each of its elements, but when calling the Association or Values @ Association, I have a "Too Long to Display" message, but it's just an Association of 4 TimeSeries objects with 1000 data points or so :

![image](https://github.com/user-attachments/assets/a4c802c6-4bf2-442e-ab65-7ab513690056)

This behaviour is not always encountered. For example, here, I can display an Association of 4 TimeSeries of more than 2 millions datapoints each :

![image](https://github.com/user-attachments/assets/71b2fdfc-f6b4-4a7f-9033-c2a373f4cf5d)

**Comment by JerryI** [comment]
Hi @Hachann !
Hmm... Does it occur still if you drop 1 key from `trBars`?

**Comment by Hachann** [comment]
> Hi @Hachann ! Hmm... Does it occur still if you drop 1 key from `trBars`? Like `KeyDrop[trBars...`

![image](https://github.com/user-attachments/assets/e881d5d5-8855-4c0d-8da6-f3c848e66822)

**Comment by JerryI** [comment]
![Screenshot 2024-09-09 at 15 01 56](https://github.com/user-attachments/assets/bb287bf8-92a5-4e48-a785-eaf8bcf4fe05)

Now I see. Below a threshold of ~1000 items (depends on the structure) inside a `TimeSeries`, the data is stored inside a cell. When You have multiple of those items, the cell gets really large inside and a post-processor decided to cut it.

However, if you exceeded the limits already within a single `TimeSeries` (labelled by `Data on Kernel`), there is no longer an actual data, only a temporal reference, which costs nothing. Therefore you can have many more of such symbols inside a the output of a single cell.

**Comment by JerryI** [comment]
I think we should lower this limit even more, since a single instance of  `TimeSeries` with only 1000 entities already causes lags, when I try to type inside the same cell on my M1 Air.

**Comment by Hachann** [comment]
I see !

As for my use cases, working heavily with TimeSeries, displaying a TimeSeries object (or more) in an output in Mathematica lets me : 

1. check that I do get a TimeSeries as the result of a computation which should output a TimeSeries,
2. quickly see if data points are all numeric (blue curve representation) or not (gray curve),
3. quickly check TimeSeries properties like PathLength, Interpolation and TemporalRegularity, which I can see in Mathematica after clicking "+" button in the TimeSeries object.

The 2nd point is already a feature in WLJS, which is nice :) 

So yeah, I don't think it's very useful to store values in the frontend, given my understanding of your input. One should use the operator form ["Values"] on the TimeSeries to visualize them, I believe.

Thank you !

**Comment by JerryI** [comment]
Fixed in a new release of `wljs-editor`
