### ISSUE TITLE
CMD+P not opening the command palette

### ISSUE THREAD

**Issue by Kreeblah** [JerryI/wolfram-js-frontend#287]
I just installed WLJS and Wolfram Engine onto an M1 Max Macbook Pro running macOS 15.0.1 through Homebrew, and I'm looking at the getting started tutorials.  A2 mentions that CMD+P should be able to open the command palette, but that key combo doesn't seem to do anything for me.

Is there something else I need to do in order to enable that?

**Comment by JerryI** [comment]
All external hotkeys are set on the startup. It is known issue, that when you start for the first time (after installation), it downloads libraries/plugins and UI might not know about all key bindings from external plugins.

Just restart an App and it will work.

**Comment by JerryI** [comment]
<img width="689" alt="Screenshot 2024-10-06 at 11 44 57" src="https://github.com/user-attachments/assets/6b993ef9-3fa6-452f-a338-7ee92e25d183">

palette will also open if you click on it

**Comment by Kreeblah** [comment]
Oh, yep.  Restarting the application got that working just fine.  I guess I didn't quite get the right keywords when searching through the old issues here before opening this one.  Sorry about that.

**Comment by JerryI** [comment]
You are welcome!

I will reopen this one just not to forget about this issue ;) In principle it can be solve by rescanning plugins after the startup...

**Comment by JerryI** [comment]
PS: Not many people reach `tutorial` section in examples. Please feel free to leave your feedback :)
