### ISSUE TITLE
Dynamic libraries are broken (Linux Manjaro)

### ISSUE THREAD

**Issue by I-am-Rudi** [JerryI/wolfram-js-frontend#295]
I'm having problems with the new release. I have tried different ways of installation (.deb, AppImage, AUR) and several versions of WolframEngine. I have also tried two different accounts with Developer Licenses but I still always end up with this output:

```
checking the installation folder...
/home/rudi/.config/wljs-notebook

Current version: 2.5.8
You are using the latest release

Starting wolframscript by path: wolframscript

Wolfram Language 14.1.0 Engine for Linux x86 (64-bit)
Copyright 1988-2024 Wolfram Research, Inc.


In[1]:= 
>> LPM >> project directory >> /home/rudi/.config/wljs-notebook

>> LPM >> last updated >> Sat 19 Oct 2024 15:56:54

>> CSockets >> Unix >> Linux-x86-64

>> CSockets >> Unix >> Loading library... LLink JustTryToFind


LibraryFunction::libload: 
   The function run_uvloop was not loaded from the file 
    /home/rudi/.config/wljs-notebook/wl_packages/KirillBelov_CSockets/LibraryR
     esources/7/Linux-x86-64/csockets.so.

>> CSockets >> Unix >> It did not work! LLink 7
>> CSockets >> Unix >> Trying LLink 6


LibraryFunction::libload: 
   The function run_uvloop was not loaded from the file 
    /home/rudi/.config/wljs-notebook/wl_packages/KirillBelov_CSockets/LibraryR
     esources/6/Linux-x86-64/csockets.so.
>> CSockets >> Unix >> Loading process failed. LLink 6

The Wolfram Engine exited because of a license error.

Process exited with code 255
```

**Comment by JerryI** [comment]
And could you please also check if this file exists

```
/home/rudi/.config/wljs-notebook/wl_packages/KirillBelov_CSockets/LibraryResources/7/Linux-x86-64/
```

**Comment by I-am-Rudi** [comment]
The file `/home/rudi/.config/wljs-notebook/wl_packages/KirillBelov_CSockets/LibraryResources/7/Linux-x86-64/csockets.so` exists  and the distro is Manjaro.

Also thanks for the quick response.

**Comment by JerryI** [comment]
> Manjaro

In principle all dependencies should have been statically linked. But just to exclude one possibility, could you, please, install
- `libuv`
- `avachi-daemon` (recommended by WRI)

**Comment by I-am-Rudi** [comment]
Sorry I didn't have time to try it out earlier. The missing library seems to have been libuv. Everything seems to work again now, thank you.
