### ISSUE TITLE
Output being moderately sized list takes too long to appear on the screen and slows down ui of notebook

### ISSUE THREAD

**Issue by zvnkk** [JerryI/wolfram-js-frontend#303]
using Subdivide[0,1,1000] gives "too long to display cell" and that is good, however Subdivide[0,1,400] blocks ui and takes too much to display. latter could take up to a minute to dislay and keyboard and mouse motions become really slow

**Comment by JerryI** [comment]
Yes, some types of syntax sugar might be expensive. The current limit is 30000 characters, we reduced it to 4000 by the default. It somewhat is an equivalent of `Subdivide[0,1, 100]`

Now it is controllable parameter via symbol [$OutputCharactersLimit](https://jerryi.github.io/wljs-docs/frontend/Reference/Decorations/$OutputCharactersLimit)

**Comment by zvnkk** [comment]
setting variable  $OutputCharactersLimit from editor to number like 100 does not seem to limit output

**Comment by JerryI** [comment]
> setting variable  $OutputCharactersLimit from editor to number like 100 does not seem to limit output 

Did you get a new update?

**Comment by zvnkk** [comment]
updated just now, and it works, thanks a lot 🔥
