### ISSUE TITLE
'uv.h' file not found

### ISSUE THREAD

**Issue by MitsuhaMiyamizu** [JerryI/wolfram-js-frontend#31]
Hello,
    I'm a macOS user and after I cloned this repository and run the example code, 

```wolframscript -f Scripts/run.wls```

I got the error message:

```
>> LPM >> extracting...
>> LPM >> copying... from /Users/blahblah/wolfram-js-frontend/___temp/JerryI-wl-wsp-74ceeb2/ to /Users/blahblah/wolfram-js-frontend/wl_packages/JerryI_WSP
LPM >> finished!
>> LPM >> fetching a zip archive from the master branch...
>> LPM >> extracting...
>> LPM >> copying... from /Users/blahblah/wolfram-js-frontend/___temp/JerryI-wl-misc-e2185c6/ to /Users/blahblah/wolfram-js-frontend/wl_packages/JerryI_Misc
LPM >> finished!
/Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/Source/Unix/socket_listener.c:6:10: fatal error: 'uv.h' file not found
#include <uv.h>
         ^~~~~~
1 error generated.

CreateLibrary::cmperr: Compile error: /Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/Source/Unix/socket_listener.c:6:10: fatal error: 'uv.h' file not found

LibraryFunction::noopen: Cannot open /Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/LibraryResources/MacOSX-ARM64/socket_listener.dylib.

LibraryFunction::noopen: Cannot open /Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/LibraryResources/MacOSX-ARM64/socket_listener.dylib.

LibraryFunction::noopen: Cannot open /Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/LibraryResources/MacOSX-ARM64/socket_listener.dylib.

General::stop: Further output of LibraryFunction::noopen will be suppressed during this calculation.
/Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/Source/Unix/socket_listener.c:6:10: fatal error: 'uv.h' file not found
#include <uv.h>
         ^~~~~~
1 error generated.

CreateLibrary::cmperr: Compile error: /Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/Source/Unix/socket_listener.c:6:10: fatal error: 'uv.h' file not found

Global`NotebookStoreKernelSymbol::shdw: Symbol NotebookStoreKernelSymbol appears in multiple contexts {Global`, JerryI`WolframJSFrontend`Notebook`}; definitions in context Global` may shadow or be shadowed by other definitions.
Checking missing packages...
# the package wljs-editor is missing
fetching the data...
url: https://github.com/JerryI/wljs-editor/zipball/master
```

And I have already installed libuv using brew:

```
Warning: libuv 1.46.0 is already installed and up-to-date.
To reinstall 1.46.0, run:
  brew reinstall libuv
```

Is there a way to point to libuv library manually during  compilation by mathematica  ```CreateLibrary``` ?

**Comment by JerryI** [comment]
Hello @MitsuhaMiyamizu,
It looks like a bug, since CSockets is shipped with precompiled binaries for MacOS.
I will check it today

PS: Thank you for your donation! It matters a lot ❤️

**Comment by JerryI** [comment]
In principle you can change the path to that file by editing
```
wl_packages/KirillBelov_CSocketListener/Scripts/BuildLibrary.wls
```

there is a variable called `MACOSXLIBUVPATH`

**Comment by JerryI** [comment]
@MitsuhaMiyamizu, could you, please, share your CPU architecture?
I suspect that you are running M1/2 or something like that ;)

**Comment by MitsuhaMiyamizu** [comment]
Thanks for your reply, I'll try this solution :)

**Comment by JerryI** [comment]
If it compiles well, I would like to ask you to share the binaries that will appear in `wl_packages/KirillBelov_CSocketListener/LibraryResources`. So that I can include them to the repository and other users with M2 chip won't have to compile them again.

**Comment by MitsuhaMiyamizu** [comment]
Ah I can see the path in the file you've mentioned, it seems you hardcoded them:)

```
#!/usr/bin/env wolframscript
(* ::Package:: *)

LINUXLIVUVPATH = "/home/kirill/Downloads/libuv-1.46.0/build/libuv.so"
MACOSXLIBUVPATH = "/usr/local/lib/libuv.a"

Get["CCompilerDriver`"]; 

(*
$CCompiler={"Compiler"->GenericCCompiler,
 "CompilerInstallation"->"C:\\mingw64\\bin",
 "CompilerName"->"gcc.exe",
 "ShellOutputFunction"->Print}
```

After installation by homebrew, libuv will be put in ```/opt/homebrew/lib/``` ,
but after I tried to modify the ```MACOSXLIBUVPATH``` in the file above to this:
```MACOSXLIBUVPATH = "/opt/homebrew/lib/libuv.a"```
it still emit the error:

```
/Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/Source/Unix/socket_listener.c:6:10: fatal error: 'uv.h' file not found
#include <uv.h>
         ^~~~~~
1 error generated.```

**Comment by JerryI** [comment]
@MitsuhaMiyamizu, I would give a try to completely bypass the checks by replacing a file with following content

```mathematica
#!/usr/bin/env wolframscript

MACOSXLIBUVPATH = "/opt/homebrew/lib/libuv.a"


Echo[$OperatingSystem]; 

OSLibs = {};
OSPath = "Unix";

OSLinker = {MACOSXLIBUVPATH<>" -pthread"};

Block[{$directory, $libSrc, $libDir}, 
	$directory = DirectoryName[If[$InputFileName == "", 
		NotebookFileName[], 
		$InputFileName
	], 2]; 


	$libSrc = File[FileNameJoin[{
		$directory, 
		"Source", 
		OSPath,
		"socket_listener.c"
	}]]; 


	$libDir = FileNameJoin[{
		$directory, 
		"LibraryResources", 
		$SystemID
	}]; 


	If[!FileExistsQ[$libDir], CreateDirectory[]];


	Get["CCompilerDriver`"]; 

	CreateLibrary[$libSrc, "socket_listener" , "TargetDirectory" -> $libDir, "Debug"->True, "LinkerOptions"->OSLinker,	"Libraries"->OSLibs]
]; 

```


and in a file `wl_packages/KirillBelov_CSocketListener/Kernel/CSocketListener.wl` a line `94`

```mathematica
$libFile = FileNameJoin[{
	$directory, 
	"LibraryResources", 
	$SystemID, 
	"socket_listener.dylib"
}]; 
```

Such a pity, I don't have M1 machine nearby ;(

**Comment by MitsuhaMiyamizu** [comment]
It works this time.

```
>> LPM >> fetching info by KirillBelovTest/TCPServer on a Github...
>> LPM >> installed 109 remote 109
>> LPM >> will be UPDATED: 0
>> MacOSX

LibraryFunction::noopen: Cannot open /Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/LibraryResources/MacOSX-ARM64/socket_listener.dylib.

LibraryFunction::noopen: Cannot open /Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/LibraryResources/MacOSX-ARM64/socket_listener.dylib.

LibraryFunction::noopen: Cannot open /Users/blahblah/wolfram-js-frontend/wl_packages/KirillBelov_CSocketListener/LibraryResources/MacOSX-ARM64/socket_listener.dylib.

General::stop: Further output of LibraryFunction::noopen will be suppressed during this calculation.
>> MacOSX

Global`NotebookStoreKernelSymbol::shdw: Symbol NotebookStoreKernelSymbol appears in multiple contexts {Global`, JerryI`WolframJSFrontend`Notebook`}; definitions in context Global` may shadow or be shadowed by other definitions.
checking the package /Users/blahblah/wolfram-js-frontend/Packages/wljs-cells/package.json...
* update meta-data from it
checking the package /Users/blahblah/wolfram-js-frontend/Packages/wljs-editor/package.json...
* update meta-data from it
```

As far as I can recall, there's a project called wolfram-language-notebook, it actually uses ZMQ to bridge the gap between frontend (notebook) and backend (wolfram kernel).

**Comment by JerryI** [comment]
> It works this time...at least I can open 127.0.0.1:8090 and see the frontend webpage, but I cannot add a new notebook and have nothing responded by clicking every button on the page, i can only unfold the path on the left side of the page.. For troubleshooting, there are some warnings/errors you may be interested i

This actually is a major drawback of using native socket, sad. 

The unfolding works since it uses Websockets which transport only small portions of data, unlike http server.

Do not worry about it, i have already found M1 machine ;)

**Comment by JerryI** [comment]
a guy @khabibullet donated his M1 Mac, so I have updated CScokets library.
On the startup it should automatically extract and install a new 1.0.9 version. 

If not, just remove `wl_packages` and `wl_packages_lock` directory/file and then it will install fresh packages.

**Comment by MitsuhaMiyamizu** [comment]
This just works (image 1), but the notifications keep popping up by the JS console on the right side are a bit annoying (image 2), anyway this runs very smoothly, let's celebrate for this milestone you achieved!
<img width="681" alt="2023-08-14 23 07 02" src="https://github.com/JerryI/wolfram-js-frontend/assets/9009218/331c9325-b210-4114-9b02-5e82b5ce2f0e">
<img width="621" alt="2023-08-14 23 11 42" src="https://github.com/JerryI/wolfram-js-frontend/assets/9009218/26b12790-7207-4c22-9fe2-8dba034d434a">

**Comment by JerryI** [comment]
Hah! Glad to see that!
By the way, I did not know that filling option on plots actually works :D

PS: Regarding notifications, you are right, I should have been put them into debug mode only.

**Comment by MitsuhaMiyamizu** [comment]
Actually if you looked at the first image very carefully you will find another strange thing, that is, the precision of the float is not controlled by ```N[]``` any more using this frontend, it seems this function is handled by the original/official implementation of frontend of mathematica or wolfram engine. Don't know why they will do this, maybe because the output can be easily manipulated at the frontend rather than the backend?

**Comment by JerryI** [comment]
> Don't know why they do this, maybe because the output can be easily manipulated at the frontend rather than the backend?

I have completely forgot, that I turned this feature off for any Export functions

```mathematica
$NumberMarks = False
```

that, in principle, should affect numbers in the output cells. The problem was, I did not managed to find a way to efficiently parse Mathematica's numbers representation in Javascript. That might not be a big problem, since inside Wolfram Kernel it still uses the original full representation.

**Comment by userrand** [comment]
> The problem was, I did not managed to find a way to efficiently parse Mathematica's numbers representation in Javascript.

Not sure what you meant but maybe the mathematica function [RealDigits](https://reference.wolfram.com/language/ref/RealDigits.html) could help
