### ISSUE TITLE
unable to install wljs notebook on macos sequoia

### ISSUE THREAD

**Issue by kaleidic200** [JerryI/wolfram-js-frontend#312]
Unable to install wljs notebook on macos sequoia. Successfully installed wolfram engine and wolfram script, but wljs notebook gets into a loop repeatedly asking whether wolfram engine is installed, then loads browser and navigates to wolfram engine download page

**Comment by JerryI** [comment]
We have updated the releases, please, try to redownload a binary file for your arch.
It should work now.

**Comment by JerryI** [comment]
Please reopen if the problem is still there.
