### ISSUE TITLE
Unable to Run WLJS on Ubuntu 24 LTS

### ISSUE THREAD

**Issue by wangyenshu** [JerryI/wolfram-js-frontend#314]
Mathematica version: 14.0.0
OS: Ubuntu 24 LTS
WLJS version 2.6.0 deb
Behavior: WLJS window hangs on loading state.
[System.log](https://github.com/user-attachments/files/17965634/System.log)

**Comment by JerryI** [comment]
If you click `Reinstall` on the startup, does it start to fetch some packages?

**Comment by JerryI** [comment]
If you have powerful firewall, which blocks some github servers, you can use `offline` [bundle](https://github.com/JerryI/wolfram-js-frontend/releases/tag/2.6.0), and hit `reinstall` after installation.

PS: I checked on Debian with no internet connection.

**Comment by wangyenshu** [comment]
The offline bundle works. Thanks.
