### ISSUE TITLE
Kernel fails to start

### ISSUE THREAD

**Issue by sw1sh** [JerryI/wolfram-js-frontend#32]
Getting errors like this:
```
...
Kenrel is not ready yet to attach notebook id
sh: /Applications/Wolfram: No such file or directory
sh: line 0: exec: /Applications/Wolfram: cannot execute: No such file or directory
...
```

$InstallationDirectory contains spaces: `/Applications/Wolfram Desktop 13.3.1.app/Contents`

**Comment by JerryI** [comment]
Thanks for the feedback! That should be an easy fix
[](https://github.com/JerryI/wolfram-js-frontend/commit/906df7abdb9a168aa1d732cb8082ba2b5fc8dfb6)
