### ISSUE TITLE
Failure with custom message

### ISSUE THREAD

**Issue by Hachann** [JerryI/wolfram-js-frontend#322]
Hi guys,

First, Happy holidays!

`Failure["Custom Failure", <|"Message" -> "huhu"|>]`  generates a message :

> unknown WL expression. Error at Frame...

Thanks.

**Comment by JerryI** [comment]
Hi! Happy New Year! 🥳

<img width="720" alt="Screenshot 2024-12-26 at 21 48 47" src="https://github.com/user-attachments/assets/23391adb-58a7-4f28-9e3f-70d282636a22" />


Fixed in [commit](https://github.com/JerryI/wljs-editor/commit/aaa62958c18ec663f4537a35e4bd69266615f664)
