### ISSUE TITLE
feature request: In place evaluation

### ISSUE THREAD

**Issue by userrand** [JerryI/wolfram-js-frontend#4]
Is it possible to do in place evaluation in the notebook cell ? (for example in an expression 4+2+6, select 4+2, then use ctrl+shift+enter and the 4+2 evaluates to 6 without evaluating the entire cell).

Someone already tried doing this with code mirror 6 here: https://observablehq.com/@tophtucker/eval-in-place (or google in place evaluation codemirror).

### Why ?

I like in place evaluation as it allows checking the definition or full definition of a function by using Definition or FullDefinition with in place evaluation which allows me to check the entire function definition while remaining in the same notebook cell (rather than creating a new cell that I then have to delete or searching for the function in the notebook).

In place evaluation can also be used to track a variable x during the evaluation by using Dynamic and placing the variable in a comment like (* Dynamic[x] *) then select Dynamic[x] and ctrl+shift+ enter then evaluate the notebook cell to see x changing inside the comment. Example:

`(* Dynamic[x] *) x = 0; Do[x++; Pause[1], 4]`

**Comment by JerryI** [comment]
Yep. It is possible to implement! 
I will think about it

**Comment by userrand** [comment]
Awesome
