### ISSUE TITLE
[Feature Request] Infinite Canvas interface

### ISSUE THREAD

**Issue by dishmint** [JerryI/wolfram-js-frontend#53]
Vertical layouts can restrict organizational flexibility. 

There are times when I'd like to have a set of cells adjacent to my working location in a nb, so I don't have to scroll 'all the way up' or down. In Mathematica, I suppose one could copy and paste cells into a new nb and have two nbs open at once, or create some sort of palette that presents 'pinned' cells, but I think an infinite canvas is a much better solution, and presumably would be easier to implement with an open project than working with M's frontend itself.

In the pkm app Obsidian there's a feature called [Canvas](https://obsidian.md/canvas).

Users can create cards in an infinite workspace, and each card is a kind of note. Here, in the js-frontend, cards could be an embedded nb or groups of individual cells. 

Having free cells / nbs would help with grouping ideas or approaches, for example, one can have areas for function prototyping, function exposition, and maybe another for relevant links to papers etc.

Crude example:
<img width="500" alt="A notebook describing arithmetic on expressions with head expr" src="https://github.com/JerryI/wolfram-js-frontend/assets/18143853/9f7efb24-d03d-458c-a85d-eb54ec3a9a48">

<img width="500" alt="Crude example of an infinite canvas notebook" src="https://github.com/JerryI/wolfram-js-frontend/assets/18143853/e44a276b-72ec-4d8f-bc5c-8c28a6a6dda5">

**Comment by dishmint** [comment]
One thing I overlooked is order of evaluation 🫠

**Comment by JerryI** [comment]
Hi @dishmint! This is a nice idea to be implemented as sort of extension.

I see you are looking for OneNote 2016 on steroids heh. :)

I tried yesterday using attribute `position:absolute` and `d3.drag` applied to a cell's container and it looks quite promising. 

We will share the results when they will be ready more or less ;)

**Comment by JerryI** [comment]
some preliminary results
[Canvas.txt](https://github.com/JerryI/wolfram-js-frontend/files/13244871/Canvas.txt)

https://github.com/JerryI/wolfram-js-frontend/assets/4111822/49e20ba9-72f0-4a0f-8138-ce4121a741b1


(just change the extension to `.wln` and evaluate initializaition cells)

But this **idea might be doomed because of** [Issue](https://github.com/codemirror/codemirror5/issues/2443) with an editor

**Comment by dishmint** [comment]
Dang! It's cool to see a preliminary version at least.

Fingers crossed, I think this will be very useful ext to nbs.

**Comment by userrand** [comment]
Nice idea.

For the scrolling problem you can maybe use cell tags with [NotebookLocate](https://reference.wolfram.com/language/ref/NotebookLocate.html).

The following [stack exchange answer] (https://mathematica.stackexchange.com/a/283313/86543) provides details on how to use `NotebookLocate` with the usual Mathematica notebooks. 

Not sure if there is a tag feature in Jupyter notebooks with Jupyter, Vscode or Jupyter lab.

**Comment by JerryI** [comment]
>
> 
> 
> 
> But this **idea might be doomed because of** [Issue](https://github.com/codemirror/codemirror5/issues/2443) with an editor
> 
> 

Ok. Good news, looks like it was fixed 2mo ago [link](https://github.com/codemirror/dev/issues/324#issuecomment-1702571472)
