### ISSUE TITLE
Fail to start due to connection issue

### ISSUE THREAD

**Issue by ytskuh** [JerryI/wolfram-js-frontend#57]
In places where github is blocked (i.e. behind a powerful firewall), although the resources can be fetched through a proxy, the program will try to ping github.com and refuse to start
```
>> LPM >> project directory >> /home/fred/wolfram-js-frontend/Packages/wljs-wlx-support
>> LPM >> fetching paclet infos...
>> LPM >> fetching info by JerryI/wl-wlx on a Github...
>> LPM >> checking cached
$Aborted
PingTime::ptimeout: No ping echo received from host github.com within the specified timeout.
>> LPM >> ERROR! no internet connection to github.com!
>> LPM >> ERROR! no cache found ;()
```
This heavy reliation on internet connection is a painful experience...

**Comment by JerryI** [comment]
[This](https://github.com/JerryI/wolfram-js-frontend/releases/tag/1.0.1) should help 
I tested it with my mac
- clean install
- no internet connection
- all examples are working

**Comment by ytskuh** [comment]
Thanks for that. The program can start now but with blank window. I will close this issue and open a new one though
