### ISSUE TITLE
WLJS on Mac M1 install buggy

### ISSUE THREAD

**Issue by gganapat** [JerryI/wolfram-js-frontend#61]
Hi, your product looks promising, but I just couldn't get it installed (Desktop version) on my Mac M1. Tried multiple times over a period of months, but no go.

**Comment by JerryI** [comment]
Hi! Sorry to hear that.
Actually I am also using it on M1 machine and had some issues with the latest WL update. 

I would like to ask to share the startup log file

> You can find it using "File" (or top bar menu for Mac users) menu, then click on "Locate AppData" (installation directory), where in the root directory there is a file 2MinutesLog.txt. Please send it to us.

It might contain some private information, please consider that.

**Comment by JerryI** [comment]
and, where did it stuck, by the way?

**Comment by JerryI** [comment]
By the experiment I have found
- M1 + WL 13.3 = crash (on FunctionCompile used in HTTP Server)
- M1 + WL 13.2 = download manager return `Pointer = Null`
- M1 + WL 13.1 = crash
- M1 + WL. 13.01 = download manager return `Pointer = Null`



The only solution for Wolfram Engine to work on M1 I found
```bash
brew install --cask wolfram-engine    
```

**Comment by JerryI** [comment]
Ok. Soon, we will release the client app that takes care about all this installation hassle

**Comment by tunesmith** [comment]
Just echoing; I tried today and got "“WLJS Notebook” is damaged and can’t be opened. You should move it to the Trash."

I'm on an M3 Pro.

**Comment by JerryI** [comment]
> Just echoing; I tried today and got "“WLJS Notebook” is damaged and can’t be opened. You should move it to the Trash."
> 
> I'm on an M3 Pro.

Hm. I recompiled it again using fresh Electron version (could be a problem with Electron version & OSX).
Could you, please, try [this version](https://github.com/JerryI/wolfram-js-frontend/releases/download/1.0.7/WLJS.Notebook-0.7.1-arm64.dmg.zip) ?

**Comment by aclysma** [comment]
I am having the same problem ""“WLJS Notebook” is damaged and can’t be opened. You should move it to the Trash.", also on M3 with macOS Sonoma on WL 13.3

**Comment by JerryI** [comment]
> I am having the same problem ""“WLJS Notebook” is damaged and can’t be opened. You should move it to the Trash.", also on M3 with macOS Sonoma on WL 13.3

Hi @aclysma ,
One more attempt. 

Could you please try a [universal build](https://github.com/JerryI/wolfram-js-frontend/releases/download/1.0.7/WLJS.Notebook-0.7.2-universal.dmg) for OSX?

On Electrons troubleshooting forums, people blame the latest stable Sonoma release. I am actually on Sonoma Beta for similar reasons, however, hope this fix above will help you without taking a risk on using beta-channel.

**Comment by tunesmith** [comment]
FWIW, this one worked better for me. I still get the "could not verify it was free of malware" message, but control-clicking on the app works. Loading documents: I still got a series of popups the first time I loaded a doc, but loading more documents after that point was smooth.

**Comment by gganapat** [comment]
I tried the above and initially got the message that the WolframEngine couldn't be found and asked me to locate it, which I did. Then it started and froze at this point
<img width="617" alt="Screenshot 2024-01-19 at 6 49 31 PM" src="https://github.com/JerryI/wolfram-js-frontend/assets/46061218/8ab98cf1-381f-4b72-beb0-4c945cefb39a">

**Comment by gganapat** [comment]
Moving package to Trash and reinstalling didn't change anything, it still sticks at above.

**Comment by aclysma** [comment]
0.7.2 was able to launch, thanks! My experience was similar to what @tunesmith described.

**Comment by gganapat** [comment]
> Hi! Sorry to hear that. Actually I am also using it on M1 machine and had some issues with the latest WL update.
> 
> I would like to ask to share the startup log file
> 
> > You can find it using "File" (or top bar menu for Mac users) menu, then click on "Locate AppData" (installation directory), where in the root directory there is a file 2MinutesLog.txt. Please send it to us.
> 
> It might contain some private information, please consider that.

When I checked the file I see this --

```
checking the installation folder...
/Users/gani/Library/Application Support/wljs-frontend

Current version: 0.7.2
You are using the latest release

Starting wolframscript by path: /Applications/Wolfram Engine.app/Contents/Resources/Wolfram Player.app/Contents/MacOS/WolframKernel

Wolfram Language 13.3.0 Engine for Mac OS X ARM (64-bit)
Copyright 1988-2023 Wolfram Research, Inc.
```

I had installed Mathematica 14 and there is a conflict with the Wolfram Engine. is there a way to reverse everything and start from scratch - pick which wolframengine to use?

**Comment by JerryI** [comment]
> 
> I had installed Mathematica 14 and there is a conflict with the Wolfram Engine. is there a way to reverse everything and start from scratch - pick which wolframengine to use?

Sure! Please, remove `configuration.ini` in AppData folder (./conf/wljs-frontend) and restart

**Comment by gganapat** [comment]
Ok that worked! Now, I can play around.Thx!On Jan 20, 2024, at 10:47 AM, Kirill Vasin ***@***.***> wrote:﻿

I had installed Mathematica 14 and there is a conflict with the Wolfram Engine. is there a way to reverse everything and start from scratch - pick which wolframengine to use?

Sure! Please, remove configuration.ini in AppData folder (./conf/wljs-frontend) and restart

**Comment by gganapat** [comment]
Ok, still a problem. Once I pointed to the wolframscript in /usr/local/bin/wolframscript, the program launched and I was able to view all example files. But I was not able to evaluate any new wolfram expression - nothing happens.

**Comment by JerryI** [comment]
Do you have a green line on the left side between the sidebar and notebook?

Also in logs, when you start a kernel from the menu it shown what happen (you can attach a screenshot or just text from logs..)

Due to buggy licensing of Wolfram Engine, sometimes Wolfram Engine blocks second kernel to be launched...

**Comment by gganapat** [comment]
ok, I re-activated the free Wolfram Engine (13.3) and pointed to it instead of the MM v14 now it works. Thx!

**Comment by JerryI** [comment]
[Still not fixed](https://github.com/electron-userland/electron-builder/issues/5850)

**Comment by JerryI** [comment]
Solutions are listed in [docs](https://jerryi.github.io/wljs-docs/frontend/Troubleshooting/Apple%20Silicon)

**Comment by JerryI** [comment]
Fixed in [signed release](https://github.com/JerryI/wolfram-js-frontend/releases/tag/2.2.6)
Now we have all certificates from Apple
