### ISSUE TITLE
Sidebar randomly overflows sometimes

### ISSUE THREAD

**Issue by walking-octopus** [JerryI/wolfram-js-frontend#64]
Sometimes when running certain cells, probably related to plotting/canvas, the sidebar expands into this mess.

I'm unable to consistently reproduce it, but it happens often enough on its own, seemingly correlated with evaluation of certain graphics cells.

- __Wolfram__: "13.0.1 for Linux x86 (64-bit) (January 29, 2022)"
- __Browser__: Firefox 120.0.1 (64-bit)
- __Environment__: Running inside Ubuntu Distrobox container, wolframscript exported.
- __OS__: Fedora Kinoite `fedora:fedora/39/x86_64/kinoite 39.20231221.0`

UX wise it currently is one of the most important annoying bugs...

![Screenshot_20231224_122012](https://github.com/JerryI/wolfram-js-frontend/assets/46994949/7ac7088a-ab39-41ee-9371-df75f4a6265e)

**Comment by JerryI** [comment]
Fixed in #84
