### ISSUE TITLE
Output styling

### ISSUE THREAD

**Issue by walking-octopus** [JerryI/wolfram-js-frontend#65]
https://www.wolfram.com/language/elementary-introduction/3rd-ed/07-colors-and-styles.html

## Example:

`Style["hello", 20, #] & /@ {Red, Orange, Blue, Purple}`

### Expected output:
![image](https://github.com/JerryI/wolfram-js-frontend/assets/46994949/a6db2a77-cfc7-4512-84d9-93eda8157bbb)

## Current output:
![image](https://github.com/JerryI/wolfram-js-frontend/assets/46994949/c518ec2c-1713-4faf-8720-0787111bf836)

**Comment by JerryI** [comment]
Nice issue! :)
For now only `Background->` is [supported](https://jerryi.github.io/wljs-docs/docs/frontend/Reference/Decorations/Style). However, it can be an easy fix for font-size and color.

**Comment by JerryI** [comment]
Hm. I would like to ask you to join the discussion.
It seems, that `Style` not only decorate an expression, but also removes double quotes from string.
i.e.

not
```
"hello"
``` 

is decorated, but

```
hello
```
where `"` are hidden. But an expression is not a string, i should probably leave inner expression untouched expect for the color.

**Comment by walking-octopus** [comment]
I'm not sure, I think this tiny detail doesn't seem important enough.

Since they also demonstrate use of Style inside a plot, I suspect it may somehow related to graphics, thus no double quotes. But I'm not sure...

**Comment by JerryI** [comment]
<img width="496" alt="Screenshot 2023-12-25 at 16 49 46" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/2fb2c033-c114-4d47-b9d1-306cafc507fb">

Looks like it is quite easy to override the color and font. I will implement it

**Comment by JerryI** [comment]
Finally fixes

<img width="913" alt="Screenshot 2024-04-03 at 20 47 34" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/8f321764-1b6c-4fab-9675-f5c763b2c55d">
