### ISSUE TITLE
Audio widget

### ISSUE THREAD

**Issue by walking-octopus** [JerryI/wolfram-js-frontend#67]
https://reference.wolfram.com/language/ref/Audio.html

## Test

`ListPlay[RandomReal[1, {5000}]]`

### Expected output:

![image](https://reference.wolfram.com/language/ref/Files/ListPlay.en/1.png)

### Current output:

An raw simplified expression.

**Comment by JerryI** [comment]
Primitively fixed in [this commit](https://github.com/JerryI/wljs-editor/commit/2d3c173804a622d374b792d6bc3551a0c33f2152)

<img width="547" alt="Screenshot 2024-03-19 at 20 15 26" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/338d9f2e-a3c1-41b6-994b-97edb4c6c983">
