### ISSUE TITLE
PlotLegends and PlotLabels not working correctly

### ISSUE THREAD

**Issue by LoganJFisher** [JerryI/wolfram-js-frontend#69]
For example:

`Plot[{Sin[x], Sin[2 x], Sin[3 x]}, {x, 0, 2 Pi}, 
 PlotLegends -> "Expressions"]`

doesn't render at all.

And

`Plot[{Sin[x], Cos[x]}, {x, 0, 2 Pi}, PlotLabels -> "Expressions"]`

Lacks the labels it's supposed to have.

![I1n2hgb](https://github.com/JerryI/wolfram-js-frontend/assets/63993409/d67a5011-f236-484a-8d60-2c31b4178599)

**Comment by JerryI** [comment]
Partially fixed using [workaround solution ](https://github.com/JerryI/wljs-editor/commit/7b2c6590bfeaa2bce188ef76117df80d82105b15)

<img width="551" alt="Screenshot 2024-03-19 at 10 40 54" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/c115bf74-ad80-407f-a6c7-25fd629d5c7c">

**Comment by JerryI** [comment]
finally fixed

<img width="673" alt="Screenshot 2024-05-06 at 20 18 19" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/f02fab2b-a4fe-4264-beee-734bf66a401e">
