### ISSUE TITLE
Cannot install because of connections issue

### ISSUE THREAD

**Issue by twesterhout** [JerryI/wolfram-js-frontend#71]
I'm having trouble installing the project:

```
{Assets, build, config.build.wl, .defaultpackages, .editorconfig, electron.css, Examples, .git, .gitattributes, .github, .gitignore, imgs, Kernel, LICENSE, log.html, main.js, package.json, package-lock.json, PacletInfo.wl, preload.js, preloadMain.js, public, README.md, rendererSrc.js, rollup.config2.mjs, rollup.config.mjs, rollup.utils.config.mjs, Scripts, .scss, Services, .shead, Src, Styles, Tests, .vscode}
13.3.0 for Linux x86 (64-bit) (June 12, 2023)
Linux-x86-64
/home/tom/Projects/wolfram-js-frontend
>> LPM version: 11
>> LPM >> project directory >> /home/tom/Projects/wolfram-js-frontend
>> LPM >> fetching paclet infos...
$Aborted>> LPM >> fetching info by JerryI/CSocketListener on a Github...

Get::noopen: Cannot open https://raw.githubusercontent.com/JerryI/CSocketListener/master/PacletInfo.wl.
>> LPM >> ERROR cannot get JerryI/CSocketListener!
>> LPM >> Abortting
```

You'd think it's internet-related, but I am connected to the internet, and doing `curl https://raw.githubusercontent.com/JerryI/CSocketListener/master/PacletInfo.wl` works just fine.

Any ideas what I'm doing wrong?

Any help debugging this issue would be highly appreciated!

**Comment by JerryI** [comment]
Hello @twesterhout !
Sorry to hear that :(

How did you run it? from console or using Electron wrapper?

In principle, frontend can work entirely without internet if you are using the second option (it comes with all libs already see #57 ).

**Comment by twesterhout** [comment]
I'm using the command line, so `wolframscript ./Scripts/run.wls`. The thing is, it seems like `wolframscript` does have internet, because I can do
```
In[1]:= PingTime["github.com"]                                                                                          
Out[1]= 12.8 milliseconds
```
So it must be something special that wolfram-js-frontend is doing.

**Comment by JerryI** [comment]
Please, check [this answer](https://github.com/JerryI/wolfram-js-frontend/issues/72#issuecomment-1899245298) at #72 
It looks like that the problem has the same roots.
