### ISSUE TITLE
Example full html code requested to integrate wolfram language in JS framework

### ISSUE THREAD

**Issue by gganapat** [JerryI/wolfram-js-frontend#80]
Hi:

My use case is to integrate wolfram code in JS framework like Svelte or even vanilla HTML/CSS/JS. It appears that you have all the pieces to make this possible. However, it is almost impossible to do so unless there is a working example included with all steps needed to make it happen. Can you please consider my request?

Thanks,
Gani -

**Comment by JerryI** [comment]
Hi @gganapat !
This is a great question. There are multiple ways on how you can do that.
It does depend if you want to keep it within the notebook or go beyond it.

In notebook is you case, when you need NPM package, then there is an extension [ESM](https://github.com/JerryI/wljs-esm-support), which allows to build any Nodejs file and run in as a script in the notebook.

## From Notebook
### WL -> JS
The direct way of calling JS from notebook:
1. Create a JS cell or ESM (see above)

```js
.js

core.MyFunction = async (args, env) => {
  const data = await interpretate(args[0], env);
  alert(data);
}
```
2. then in a standard cell evaluate the following
```mathematica
FrontSubmit[MyFunction["Hello World!"]];
```

It is also possible to send arrays, associations, in principle any WL expression like that (if the last one exists on JS side)
This is how all graphics, interactivity is implemented in WLJS Notebook.

### JS -> WL
For this case there is a special global object in JS, which uses event system

1. Assign a handler to a random event

```mathematica
EventHandler["whatever", Print];
```
2. Create a JS cell, that fires an event

```js
.js

server.emitt('whatever', '1+1');
```

If you need to build an HTML template, use `.html` or `.wlx` cell types like

```html
.html
<h1>Hello World!</h1>
```

or using WLX engine

```jsx
<h1><TextString><Now/></TextString></h1>
```

with WLX this is a different story, you can use it outside the notebook interface... see below

## Web Applications or using WL together with any web stack
An ultimate way of using making something complex with any web-frameworks [is WLX.](https://jerryi.github.io/wlx-docs/)
Basically its a template engine + full featured JS/WL framework + webserver (and WebSockets). Actually Notebook interface was built using this technology.

You have the whole freedom and the same binding between WL and JS worlds using similar patterns as shown above. For example there is a special tag

```jsx
<WebUIJSBind Event={"ev"}>
	//will be executed once
	const doc = document.body;
	
	//binding to event patterns
	this.on('Pattern 1', async (data) => {
		const assoc = await interpretate(data, {hold:true});
		const payload = await interpretate(assoc.Payload, {});
		alert(payload);
	});
</WebUIJSBind>
```

which can be called from WL's site as

```mathematica
EventFire["ev", "Pattern 1", <|"Client"->$Client, "Payload"->"Hello World!"|>]
```

or in opposite direction, when a user click a button

```jsx
<div>
	<button id="btn" type="button">Click Me!</button>
	<WebUIEventListener Id={"btn"} Event={"button"} />
</div>
```

and on the server (to handle a click)

```mathematica
EventHandler["button", Print];
```

so.. depends on you application. But React, Svelte can be included here as well.

**Comment by JerryI** [comment]
There are [some example for the case](https://jerryi.github.io/wljs-docs/docs/frontend/Advanced/JS%20Tools/Canvas) `Notebook + JS` listed in docs

**Comment by JerryI** [comment]
Also, please, check `Examples` section in a top bar menu (`Locate Examples`), there is special section called `Javascript`. There must be a few examples that show similar things I described

**Comment by gganapat** [comment]
Thank you! I am looking to use WL in a SPA (single page application) that
can be developed with Svelte (or even vanilla JS). So, I am looking for a
sample html file with has all the needed CDN script (wljs-interpretate or
whatever else is needed, and JS code to say plot some data x = {0,1,2,3,4},
performing some calculation on it, say
y= #^2& /@ x (or any WL function for example y=Sin[x]) and then plotting it
using Plotly.

Thanks for the awesome work!

gani -

**Comment by JerryI** [comment]
You are welcome!

I got your point. So basically using solely JS with no running WL Kernel on the server, right? If it is so... then ->

This map function, I am not sure if I implemented it fully in WLJS interpreter, since this small interpreter running in the browser is quite limited. `Table` is for sure implemented. 

WLJS Interpreter is used mostly for displaying numerical data, some minor calculations and connecting point between WL Kernel and Web.

Be careful, since without WL Kernel, you have no longer an access to a higher-order function like `Plot`, you will have to deal only with what they produce in the end, i.e. `Graphics`, `Line`, `RGBColor` and other primitives... An exception will be `Plotly` library, which provides `ListLinePlotly` function that can be used directly on a numerical data.

However to plot a graph, you don't need WL Kernel at all. Here is a short example

I generated it using a static WLX example `Examples/WLJSBasic/WLJSBasic.wls` that  just produces HTMLpage with all links and data. I replaced local urls with CDN and data with one, provided from a simple JS's array. You could also generate this array using an interpreter, but it would be a bit cumbersome using plain JSON syntax..

```html
<html>
    <head>
        <title>WLX Template</title>
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet" />
        <script type="module" src="https://cdn.statically.io/gh/JerryI/wljs-interpreter/dev/src/interpreter.js"></script>
        <script type="module" src="https://cdn.statically.io/gh/JerryI/wljs-interpreter/dev/src/core.js"></script>
        <script type="module" src="https://cdn.statically.io/gh/JerryI/wljs-sharedlib-d3/main/dist/kernel.js"></script>
        <script type="module" src="https://cdn.statically.io/gh/JerryI/wljs-graphics-d3/dev/dist/kernel.js"></script>
        <link href="https://cdn.statically.io/gh/JerryI/wljs-graphics-d3/dev/src/styles.css" rel="stylesheet" />
    </head>
    <body>
        <div class="min-h-full">
            <header class="bg-white shadow">
                <div class="flex items-center mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8"><h1 class="text-3xl font-bold tracking-tight text-gray-900">WLJS Basics</h1></div>
            </header>
            <main>
                <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
                    <div class="wljs-object" id="aae2bfec-8c9e-4ccf-b770-16878d13cfd5">
                    </div>
                    <script type="module">
                        const data = await interpretate(["Table", ["List", "x", ["Cos", "x"]], ["List", "x", 0, 12., 0.1]], {});
                        //or you can also generate it using pure JS...
                         
                        const global = {};
                        await interpretate(
                            [
                                "FrontEndVirtual",
                                [
                                    "List",
                                    [
                                        "Graphics",
                                        [
                                            "Line",
                                            [
                                                "JSObject",
                                                data
                                            ]

                                        ],
                                        [
                                            "Rule",
                                            "Axes",
                                            "True"
                                        ]
                                    ],
                                ],
                            ],
                            { local: {}, global: global, element: document.getElementById("aae2bfec-8c9e-4ccf-b770-16878d13cfd5") }
                        );
                    </script>
                </div>
            </main>
        </div>
    </body>
</html>

```

<img width="415" alt="Screenshot 2024-03-05 at 21 55 26" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/c6cece5b-8bf3-40a3-8d32-aedfce105112">



One drawback is that there is no WL syntax parser to JSON ever created (in JS), and WLJS interpreter only accepts WL expressions in a form of JSON. But I guess it is still quite intuitive. 

One can also use dynamics and update lines on-fly from JS, but this is another story..

**Comment by gganapat** [comment]
This is great! But actually, how will this work with a Wolfram Engine on a
server? What I was really asking was, if I could have WL code in
html/css/js call WL Engine (with WL API perhaps or whatever other way that
would work best) and execute the WL functions like Plot, etc and display
results on localhost. This would be really neat if it can be done.

gani -

**Comment by JerryI** [comment]
Of course it is possible:)

If you still want to communicate with WL Kernel, please, check [this page](https://jerryi.github.io/wlx-docs/docs/Reference/Misc/WLJSTransport). In principle the only thing required is to have a live websocket connection to a WL Kernel. You don't need the full suite of WLX for this to be happen. Just a JS script that connects to a desired port. This script is generated by a function _WLJSTransportScript_


Anyway, I will come up with some ready-to-go example later...

**Comment by gganapat** [comment]
Fantastic! Thanks! Looking forward to the sample html.Gani-Sent from my iPhoneOn Mar 6, 2024, at 1:09 AM, Kirill Vasin ***@***.***> wrote:﻿
Of course it is possible:)
If you still want to communicate with WL Kernel, please, check this page. In principle the only thing required is to have a live websocket connection to a WL Kernel. You don't need the full suite of WLX for this to be happen. Just a JS script that connects to a desired port. This script is generated by a function WLJSTransportScript
Anyway, I will come up with some ready-to-go example later...

**Comment by JerryI** [comment]
Here we go

[Archive.zip](https://github.com/JerryI/wolfram-js-frontend/files/14509072/Archive.zip)

It will generate an HTML page and spawn WS server. Just open it using any browser and then click `Evaluate`.

**Comment by JerryI** [comment]
Here we go

[Archive.zip](https://github.com/JerryI/wolfram-js-frontend/files/14509072/Archive.zip)

It will generate an HTML page and spawn WS server. Just open it using any browser and then click `Evaluate`.

**Comment by JerryI** [comment]
<img width="1368" alt="Screenshot 2024-03-06 at 12 26 16" src="https://github.com/JerryI/wolfram-js-frontend/assets/4111822/7e4ee526-82a0-4634-8d1d-cf60bce12e59">

**Comment by JerryI** [comment]
When you accomplish your goals with an app, please, share your experience with the community (wolfram and wljs). It would contribute a lot

**Comment by gganapat** [comment]
Thank you. Will do. I hope you achieve all the success you deserve.

Gani -
